version: "3.9"

services:
  postgres:
    container_name: chat
    image: postgres:16.2
    env_file:
      - ./api-chat/.env
    volumes:
      - ./api-chat/postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:8.3
    environment:
      PGADMIN_DEFAULT_EMAIL: noemail@normail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
