version: "3.9"

services:
  postgres:
    container_name: chat
    image: postgres:16.2
    env_file:
      - ./api-chat/.env
    volumes:
      - ./api-chat/postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:8.3
    environment:
      PGADMIN_DEFAULT_EMAIL: noemail@normail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

  backend:
    container_name: backend
    build: ./api-chat
    restart: always
    env_file:
      - ./api-chat/.env
    command: npm run start:dev
    volumes:
      - ./api-chat:/docker-backend
    ports:
      - "3000:3000"
    depends_on:
      - postgres
  
  frontend:
    container_name: frontend
    build: ./Perfection-chat
    restart: always
    command: npm run start
    volumes:
      - ./Perfection-chat:/docker-frontend
    ports:
      - "4200:4200"